### ISSUE TITLE
[WvW Map] WvW Green border garrison shows Blue border garrison information

### ISSUE THREAD

**Issue by InAGiiZ** [rediche/gw2-ninja#52]
### Description
WvW Green border garrison shows Blue border garrison information.

### Steps to reproduce

1. Go to https://gw2.ninja/wvw/map and select any server  
2. Click on the green border garrison  
3. Click on the blue border garrison  

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [X] Edge
- [ ] IE 11
- [ ] IE 10

### Additional information  
Green border garrison id: 95-37 sector_id 992  
Blue border garrison id: 96-37 sector_id 976  
https://api.guildwars2.com/v2/wvw/objectives?ids=96-37,95-37

**Comment by rediche** [comment]
This issue has been fixed. It will be online with next deployment.
